CREATE TABLE IF NOT EXISTS school (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS expense (
  id SERIAL PRIMARY KEY,
  school_id INTEGER NOT NULL REFERENCES school(id),
  month_year TEXT NOT NULL,
  expense_name TEXT NOT NULL,
  amount FLOAT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS meal (
  id SERIAL PRIMARY KEY,
  school_id INTEGER NOT NULL REFERENCES school(id),
  date TIMESTAMP NOT NULL,
  day_of_week TEXT NOT NULL,
  total_cost FLOAT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS meal_item (
  id SERIAL PRIMARY KEY,
  meal_id INTEGER NOT NULL REFERENCES meal(id),
  item_name TEXT NOT NULL,
  unit_price FLOAT NOT NULL,
  quantity INTEGER NOT NULL,
  total FLOAT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS student (
  id SERIAL PRIMARY KEY,
  school_id INTEGER NOT NULL REFERENCES school(id),
  student_id TEXT NOT NULL,
  system_id TEXT NOT NULL,
  name TEXT NOT NULL,
  class_department TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attendance (
  id SERIAL PRIMARY KEY,
  student_id INTEGER NOT NULL REFERENCES student(id),
  date TIMESTAMP NOT NULL,
  punch_times TEXT[] NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS school_access (
  id SERIAL PRIMARY KEY,
  school_id INTEGER NOT NULL REFERENCES school(id),
  user_id TEXT NOT NULL,
  role TEXT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
